[2025-06-08T14:16:28.612+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-08T14:16:28.654+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: large_csv_processor_dag.process_products_csv manual__2025-06-08T14:16:24+00:00 [queued]>
[2025-06-08T14:16:28.666+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: large_csv_processor_dag.process_products_csv manual__2025-06-08T14:16:24+00:00 [queued]>
[2025-06-08T14:16:28.667+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-08T14:16:28.684+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): process_products_csv> on 2025-06-08 14:16:24+00:00
[2025-06-08T14:16:28.691+0000] {standard_task_runner.py:63} INFO - Started process 2319 to run task
[2025-06-08T14:16:28.695+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'large_csv_processor_dag', 'process_products_csv', 'manual__2025-06-08T14:16:24+00:00', '--job-id', '206', '--raw', '--subdir', 'DAGS_FOLDER/csv_processor.py', '--cfg-path', '/tmp/tmpgo0pqhom']
[2025-06-08T14:16:28.697+0000] {standard_task_runner.py:91} INFO - Job 206: Subtask process_products_csv
[2025-06-08T14:16:28.760+0000] {task_command.py:426} INFO - Running <TaskInstance: large_csv_processor_dag.process_products_csv manual__2025-06-08T14:16:24+00:00 [running]> on host afb0ae728713
[2025-06-08T14:16:28.874+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='large_csv_processor_dag' AIRFLOW_CTX_TASK_ID='process_products_csv' AIRFLOW_CTX_EXECUTION_DATE='2025-06-08T14:16:24+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-08T14:16:24+00:00'
[2025-06-08T14:16:28.877+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-08T14:16:28.894+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-08T14:16:28.895+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/csv_processor.py", line 40, in process_csv_in_chunks
    with open(sql_file_path, 'w') as sql_file:
PermissionError: [Errno 13] Permission denied: './dags/sql/products_insert.sql'
[2025-06-08T14:16:28.910+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=large_csv_processor_dag, task_id=process_products_csv, run_id=manual__2025-06-08T14:16:24+00:00, execution_date=20250608T141624, start_date=20250608T141628, end_date=20250608T141628
[2025-06-08T14:16:28.924+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 206 for task process_products_csv ([Errno 13] Permission denied: './dags/sql/products_insert.sql'; 2319)
[2025-06-08T14:16:28.960+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-08T14:16:28.974+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
