[2025-06-08T14:43:24.262+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-08T14:43:24.298+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: large_csv_processor_dag.process_sales_transactions_csv manual__2025-06-08T14:38:18+00:00 [queued]>
[2025-06-08T14:43:24.307+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: large_csv_processor_dag.process_sales_transactions_csv manual__2025-06-08T14:38:18+00:00 [queued]>
[2025-06-08T14:43:24.308+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-06-08T14:43:24.324+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): process_sales_transactions_csv> on 2025-06-08 14:38:18+00:00
[2025-06-08T14:43:24.329+0000] {standard_task_runner.py:63} INFO - Started process 456 to run task
[2025-06-08T14:43:24.334+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'large_csv_processor_dag', 'process_sales_transactions_csv', 'manual__2025-06-08T14:38:18+00:00', '--job-id', '247', '--raw', '--subdir', 'DAGS_FOLDER/csv_processor.py', '--cfg-path', '/tmp/tmp1g1d9x03']
[2025-06-08T14:43:24.337+0000] {standard_task_runner.py:91} INFO - Job 247: Subtask process_sales_transactions_csv
[2025-06-08T14:43:24.394+0000] {task_command.py:426} INFO - Running <TaskInstance: large_csv_processor_dag.process_sales_transactions_csv manual__2025-06-08T14:38:18+00:00 [running]> on host f6c4201d846e
[2025-06-08T14:43:24.487+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='large_csv_processor_dag' AIRFLOW_CTX_TASK_ID='process_sales_transactions_csv' AIRFLOW_CTX_EXECUTION_DATE='2025-06-08T14:38:18+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-08T14:38:18+00:00'
[2025-06-08T14:43:24.488+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-08T14:43:24.508+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-08T14:43:24.509+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/csv_processor.py", line 40, in process_csv_in_chunks
    with open(sql_file_path, 'w') as sql_file:
PermissionError: [Errno 13] Permission denied: './dags/sql/sales_transactions_insert.sql'
[2025-06-08T14:43:24.521+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=large_csv_processor_dag, task_id=process_sales_transactions_csv, run_id=manual__2025-06-08T14:38:18+00:00, execution_date=20250608T143818, start_date=20250608T144324, end_date=20250608T144324
[2025-06-08T14:43:24.535+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 247 for task process_sales_transactions_csv ([Errno 13] Permission denied: './dags/sql/sales_transactions_insert.sql'; 456)
[2025-06-08T14:43:24.559+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-08T14:43:24.572+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
