[2025-06-08T11:04:11.071+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-08T11:04:11.106+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: large_csv_processor_dag.process_sales_transactions_csv scheduled__2025-06-07T00:00:00+00:00 [queued]>
[2025-06-08T11:04:11.115+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: large_csv_processor_dag.process_sales_transactions_csv scheduled__2025-06-07T00:00:00+00:00 [queued]>
[2025-06-08T11:04:11.116+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-06-08T11:04:11.129+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): process_sales_transactions_csv> on 2025-06-07 00:00:00+00:00
[2025-06-08T11:04:11.134+0000] {standard_task_runner.py:63} INFO - Started process 790 to run task
[2025-06-08T11:04:11.137+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'large_csv_processor_dag', 'process_sales_transactions_csv', 'scheduled__2025-06-07T00:00:00+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/csv_processor.py', '--cfg-path', '/tmp/tmpc04iond6']
[2025-06-08T11:04:11.141+0000] {standard_task_runner.py:91} INFO - Job 41: Subtask process_sales_transactions_csv
[2025-06-08T11:04:11.196+0000] {task_command.py:426} INFO - Running <TaskInstance: large_csv_processor_dag.process_sales_transactions_csv scheduled__2025-06-07T00:00:00+00:00 [running]> on host 6211e2649837
[2025-06-08T11:04:11.298+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='large_csv_processor_dag' AIRFLOW_CTX_TASK_ID='process_sales_transactions_csv' AIRFLOW_CTX_EXECUTION_DATE='2025-06-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-07T00:00:00+00:00'
[2025-06-08T11:04:11.299+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-08T11:04:11.313+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-08T11:04:11.314+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/csv_processor.py", line 40, in process_csv_in_chunks
    with open(sql_file_path, 'w') as sql_file:
PermissionError: [Errno 13] Permission denied: './dags/sql/sales_transactions_insert.sql'
[2025-06-08T11:04:11.325+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=large_csv_processor_dag, task_id=process_sales_transactions_csv, run_id=scheduled__2025-06-07T00:00:00+00:00, execution_date=20250607T000000, start_date=20250608T110411, end_date=20250608T110411
[2025-06-08T11:04:11.338+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 41 for task process_sales_transactions_csv ([Errno 13] Permission denied: './dags/sql/sales_transactions_insert.sql'; 790)
[2025-06-08T11:04:11.358+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-08T11:04:11.370+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
