[2025-06-08T14:16:28.568+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-08T14:16:28.618+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: large_csv_processor_dag.process_employees_csv manual__2025-06-08T14:16:24+00:00 [queued]>
[2025-06-08T14:16:28.631+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: large_csv_processor_dag.process_employees_csv manual__2025-06-08T14:16:24+00:00 [queued]>
[2025-06-08T14:16:28.632+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-08T14:16:28.655+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): process_employees_csv> on 2025-06-08 14:16:24+00:00
[2025-06-08T14:16:28.662+0000] {standard_task_runner.py:63} INFO - Started process 2318 to run task
[2025-06-08T14:16:28.666+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'large_csv_processor_dag', 'process_employees_csv', 'manual__2025-06-08T14:16:24+00:00', '--job-id', '205', '--raw', '--subdir', 'DAGS_FOLDER/csv_processor.py', '--cfg-path', '/tmp/tmp9slqkxg9']
[2025-06-08T14:16:28.668+0000] {standard_task_runner.py:91} INFO - Job 205: Subtask process_employees_csv
[2025-06-08T14:16:28.734+0000] {task_command.py:426} INFO - Running <TaskInstance: large_csv_processor_dag.process_employees_csv manual__2025-06-08T14:16:24+00:00 [running]> on host afb0ae728713
[2025-06-08T14:16:28.850+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='large_csv_processor_dag' AIRFLOW_CTX_TASK_ID='process_employees_csv' AIRFLOW_CTX_EXECUTION_DATE='2025-06-08T14:16:24+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-08T14:16:24+00:00'
[2025-06-08T14:16:28.852+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-08T14:16:28.869+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-08T14:16:28.870+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/csv_processor.py", line 40, in process_csv_in_chunks
    with open(sql_file_path, 'w') as sql_file:
PermissionError: [Errno 13] Permission denied: './dags/sql/employees_insert.sql'
[2025-06-08T14:16:28.884+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=large_csv_processor_dag, task_id=process_employees_csv, run_id=manual__2025-06-08T14:16:24+00:00, execution_date=20250608T141624, start_date=20250608T141628, end_date=20250608T141628
[2025-06-08T14:16:28.898+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 205 for task process_employees_csv ([Errno 13] Permission denied: './dags/sql/employees_insert.sql'; 2318)
[2025-06-08T14:16:28.930+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-08T14:16:28.951+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
